package com.nurflugel.ivygrapher;

import com.nurflugel.common.ui.Util;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import static java.awt.event.KeyEvent.VK_ESCAPE;
import static javax.swing.JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT;

public class NoDotDialog extends JDialog
{
  private JButton    buttonCancel;
  private JButton    useTextBoxButton;
  private JPanel     contentPane;
  private JButton    openFileChooserButton;
  private JTextField pathTextField;
  private File       file;

  public NoDotDialog(String dotExecutablePath)
  {
    setContentPane(contentPane);
    setModal(true);
    getRootPane().setDefaultButton(useTextBoxButton);
    pathTextField.setText(dotExecutablePath);
    useTextBoxButton.addActionListener(new ActionListener()
      {
        public void actionPerformed(ActionEvent e)
        {
          file = new File(pathTextField.getText());
          dispose();
        }
      });
    buttonCancel.addActionListener(new ActionListener()
      {
        public void actionPerformed(ActionEvent e)
        {
          onCancel();
        }
      });

    // call onCancel() when cross is clicked
    setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    addWindowListener(new WindowAdapter()
      {
        @Override
        public void windowClosing(WindowEvent e)
        {
          onCancel();
        }
      });

    // call onCancel() on ESCAPE
    contentPane.registerKeyboardAction(new ActionListener()
      {
        public void actionPerformed(ActionEvent e)
        {
          onCancel();
        }
      }, KeyStroke.getKeyStroke(VK_ESCAPE, 0), WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    openFileChooserButton.addActionListener(new ActionListener()
      {
        public void actionPerformed(ActionEvent actionEvent)
        {
          onOK();
        }
      });
    pack();
    Util.center(this);
    setVisible(true);
  }

  private void onCancel()
  {
    // add your code here if necessary
    dispose();
  }

  private void onOK()
  {
    JFileChooser fileChooser = new JFileChooser();
    int          result      = fileChooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION)
    {
      file = fileChooser.getSelectedFile();
    }

    dispose();
  }

  // --------------------------- main() method ---------------------------
  public static void main(String[] args)
  {
    NoDotDialog dialog = new NoDotDialog("Test message for not finding path");

    dialog.pack();
    dialog.setVisible(true);
    System.exit(0);
  }

  // --------------------- GETTER / SETTER METHODS ---------------------
  public File getFile()
  {
    return file;
  }

  {
    // GUI initializer generated by IntelliJ IDEA GUI Designer
    // >>> IMPORTANT!! <<<
    // DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your code!
   *
   * @noinspection  ALL
   */
  private void $$$setupUI$$$()
  {
    contentPane = new JPanel();
    contentPane.setLayout(new GridBagLayout());

    final JPanel panel1 = new JPanel();

    panel1.setLayout(new GridBagLayout());

    GridBagConstraints gbc;

    gbc         = new GridBagConstraints();
    gbc.gridx   = 0;
    gbc.gridy   = 1;
    gbc.weightx = 1.0;
    gbc.fill    = GridBagConstraints.BOTH;
    contentPane.add(panel1, gbc);

    final JPanel panel2 = new JPanel();

    panel2.setLayout(new GridBagLayout());
    gbc         = new GridBagConstraints();
    gbc.gridx   = 1;
    gbc.gridy   = 0;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.fill    = GridBagConstraints.BOTH;
    panel1.add(panel2, gbc);
    useTextBoxButton = new JButton();
    useTextBoxButton.setText("Use above path");
    gbc         = new GridBagConstraints();
    gbc.gridx   = 0;
    gbc.gridy   = 0;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.fill    = GridBagConstraints.HORIZONTAL;
    panel2.add(useTextBoxButton, gbc);
    buttonCancel = new JButton();
    buttonCancel.setText("Cancel");
    gbc         = new GridBagConstraints();
    gbc.gridx   = 1;
    gbc.gridy   = 0;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.fill    = GridBagConstraints.HORIZONTAL;
    panel2.add(buttonCancel, gbc);
    openFileChooserButton = new JButton();
    openFileChooserButton.setText("Open file chooser dialog");
    gbc         = new GridBagConstraints();
    gbc.gridx   = 0;
    gbc.gridy   = 0;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.fill    = GridBagConstraints.HORIZONTAL;
    panel1.add(openFileChooserButton, gbc);

    final JPanel panel3 = new JPanel();

    panel3.setLayout(new GridBagLayout());
    gbc         = new GridBagConstraints();
    gbc.gridx   = 0;
    gbc.gridy   = 0;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.fill    = GridBagConstraints.BOTH;
    contentPane.add(panel3, gbc);
    pathTextField = new JTextField();
    gbc           = new GridBagConstraints();
    gbc.gridx     = 0;
    gbc.gridy     = 2;
    gbc.weightx   = 1.0;
    gbc.weighty   = 1.0;
    gbc.anchor    = GridBagConstraints.WEST;
    gbc.fill      = GridBagConstraints.HORIZONTAL;
    panel3.add(pathTextField, gbc);

    final JLabel label1 = new JLabel();

    label1.setText("Please use the \"Open file chooser dialog\" button or the text box to select the ");
    gbc         = new GridBagConstraints();
    gbc.gridx   = 0;
    gbc.gridy   = 0;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.anchor  = GridBagConstraints.WEST;
    panel3.add(label1, gbc);

    final JLabel label2 = new JLabel();

    label2.setText("executable Dot file in the GraphViz distribution, or click \"Cancel\" to exit");
    gbc         = new GridBagConstraints();
    gbc.gridx   = 0;
    gbc.gridy   = 1;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.anchor  = GridBagConstraints.WEST;
    panel3.add(label2, gbc);
  }

  /** @noinspection  ALL */
  public JComponent $$$getRootComponent$$$()
  {
    return contentPane;
  }
}
